### ISSUE TITLE
Code not formatted in summary

### ISSUE THREAD

**Issue by thipages** [ArthurGareginyan/my-syntax-highlighter#1]
Hi,
I use the plugin for displaying PHP code. It works well on full articles but not on the article summary (displays as simple text). Is there an option either to display it properly or to hide it on the summary side.
Thank you.

**Comment by ArthurGareginyan** [comment]
Hi,
What method you use to display the article summary?

**Comment by thipages** [comment]
Hi,
I use the default method. I did not know that we could customize the display.
Have not found where to manage it. Can you help ?
Thank you

**Comment by ArthurGareginyan** [comment]
This is strange. I checked the code that displayed in the article summary by using the default method, and all seems well.

As far as I know, Wordpress does not have the built-in ability to customize the display of the article summary, but you can use some plugins. I use the free plugin "Advanced Excerpt"(https://wordpress.org/plugins/advanced-excerpt/) by Delicious Brains. With this plugin, the code is also displayed correctly.

**Comment by thipages** [comment]
This is working now after the advanced-excerpt plugin installation. Thank you!

**Comment by ArthurGareginyan** [comment]
You're welcome! :)
